config/routes.rb
Movimentobancario::Application.routes.draw do

  devise_for :views

  resources :produtos

  resources :prazos

  resources :grupo_eventos

  resources :eventos

  resources :contas

  resources :lancamentos
  #alterar status de confirmação do lançamento
  match "/lancamento/confirmado" => "lancamentos#confirmado"
  #filtro para listagem de lançamentos
  match "/lancamento/filtro" => "lancamentos#filtro"
  #apagar lançamento
  match "/lancamento/apagar_lancamento" => "lancamentos#apagar_lancamento"

  get "dashboard/index"

  root :to => 'dashboard#index'

  get "pages/index"

  devise_for :user
  #espera arquivo sitef
  match "/importacao/sitef" => "importacao#sitef"
  #espera arquivo softawy
  match "/importacao/softway" => "importacao#softway"
  #exibe registro do arquivo sitef
  match "/importacao/sitefExibirRegistros" => "importacao#sitefExibirRegistros"
  #processa arquivo sitef: salva registro sitef e cria lançamentos
  match "/importacao/processaRegistrosSitef" => "importacao#processaRegistrosSitef"


  
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  attr_accessible :descricao, :inativo, :limite
  has_many :lancamentos
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :debito, :descricao, :grupo_evento_id, :prazo_id
  
  has_many :lancamentos
  belongs_to :grupo_evento
  belongs_to :prazo
end

app/models/grupo_evento.rb
class GrupoEvento < ActiveRecord::Base
  attr_accessible :descricao
  has_many :eventos
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  attr_accessible :confirmado, :data, :evento, :valor, :debito, :evento_id, :conta_id, :referencia
  validates_presence_of :data, :valor, :conta
  
  belongs_to :evento
  belongs_to :conta
end

app/models/prazo.rb
class Prazo < ActiveRecord::Base
  attr_accessible :descricao, :funcao
  has_many :produtos
  has_many :evento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :descricao, :descricao_sitef, :prazo_id, :conta_id, :evento_id, :taxa, :valor_lancamento
  validates :descricao, uniqueness: true
  validates :descricao_sitef, uniqueness: true
  
  belongs_to :prazo
  belongs_to :conta
  belongs_to :evento 

  def self.descricoesSitef
  	descricoes = Array.new
  	produtos = self.find(:all, :select => 'descricao_sitef')
  	produtos.each do |produto|
  		descricoes << produto.descricao_sitef
  	end
  	return descricoes
  end
end

app/models/registro_sitef.rb
class RegistroSitef < ActiveRecord::Base
  attr_accessible :nome_produto, :nsu_sitef, :autorizador, :codi_resp, :codigo_transacao, :data_lancamen, 
	  	:estado_trasacao, :indentifi_pdv, :lancado, :nsu_host, :num_par, :numero_cartao_banco_ag_co, :valor
  validates :nsu_sitef, uniqueness: true
end

app/models/sitef_file.rb
class SitefFile < ActiveRecord::Base
  attr_accessible :arquivo, :dia_correspondente
  has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_sitef.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_sitef.prn"

validates_attachment_presence :arquivo
validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/softway_files.rb
class SoftwayFiles < ActiveRecord::Base
  	attr_accessible :arquivo, :dia_correspondente
  	has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_softway.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_softway.prn"

	validates_attachment_presence :arquivo
	validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/lancamentos_controller.rb
class LancamentosController < ApplicationController
  # GET /lancamentos
  # GET /lancamentos.json
  def index
    dataInicial = DateTime.strptime(params[:dataInicial], "%d/%m/%Y").to_s(:db)
    dataFinal = DateTime.strptime(params[:dataFinal], "%d/%m/%Y").to_s(:db)
    lancamentos = Lancamento.find(:all, :conditions => ["data < ? AND conta_id = ?", dataInicial, params[:contaId][0]])
    
    @saldo_inicial = 0

    lancamentos.each do |lancamento|
      if lancamento.evento.debito
        @saldo_inicial = @saldo_inicial - lancamento.valor
      else
        @saldo_inicial = @saldo_inicial + lancamento.valor
      end
    end

    @lancamentos = Lancamento.find(:all, 
      :conditions => ["conta_id = ? AND data BETWEEN ? AND ?", params[:contaId][0], dataInicial, dataFinal])

    saldo = @saldo_inicial

    @lancamentos.each_with_index do |lancamento, i|
      if lancamento.evento.debito
        saldo = saldo - lancamento.valor
      else
        saldo = saldo + lancamento.valor
      end
      @lancamentos[i][:saldo] = saldo
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lancamentos }
    end
  end

  # GET /lancamentos/1
  # GET /lancamentos/1.json
  def show
    @lancamento = Lancamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lancamento }
    end
  end

  # GET /lancamentos/new
  # GET /lancamentos/new.json
  def new
    @lancamento = Lancamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lancamento }
    end
  end

  # GET /lancamentos/1/edit
  def edit
    @lancamento = Lancamento.find(params[:id])
  end

  # POST /lancamentos
  # POST /lancamentos.json
  def create
    @lancamento = Lancamento.new(params[:lancamento])

    respond_to do |format|
      if @lancamento.save
        format.html { redirect_to @lancamento, notice: 'Lancamento was successfully created.' }
        format.json { render json: @lancamento, status: :created, location: @lancamento }
      else
        format.html { render action: "new" }
        format.json { render json: @lancamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lancamentos/1
  # PUT /lancamentos/1.json
  def update
    @lancamento = Lancamento.find(params[:id])

    respond_to do |format|
      if @lancamento.update_attributes(params[:lancamento])
        format.html { redirect_to @lancamento, notice: 'Lancamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lancamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lancamentos/1
  # DELETE /lancamentos/1.json
  def destroy
    @lancamento = Lancamento.find(params[:id])
    @lancamento.destroy

    respond_to do |format|
      format.html { redirect_to lancamentos_url }
      format.json { head :no_content }
    end
  end

  def apagar_lancamento
    lancamento = Lancamento.find params[:id]
    if lancamento.destroy
      render :text => true
    else
      render :text => false
    end
  end

  def confirmado
    lancamento = Lancamento.find(params[:id])
    if lancamento.confirmado
      lancamento.confirmado = false
    else
      lancamento.confirmado = true
    end
    lancamento.save

    render :nothing => true
  end

  def filtro
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/importacao_helper.rb
module ImportacaoHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prazos_helper.rb
module PrazosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sitef_helper.rb
module SitefHelper
end

app/views/lancamentos/_form.html.erb
<%= form_for(@lancamento) do |f| %>
  <% if @lancamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lancamento.errors.count, "error") %> prohibited this lancamento from being saved:</h2>

      <ul>
      <% @lancamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label 'Conta' %><br />
    <%= f.select 'conta_id', Conta.all.collect {|c| [c.descricao, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :confirmado %><br />
    <%= f.check_box :confirmado %>
  </div>
  <div class="field">
    <%= f.label 'Data de efetivação' %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :evento %><br />
    <%= f.select 'evento_id', Evento.all.collect {|e| [e.descricao, e.id]} %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
   <div class="field">
    <%= f.label :Referencia %><br />
    <%= f.text_field :referencia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lancamentos/edit.html.erb
<h1>Editing lancamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @lancamento %> |
<%= link_to 'Back', lancamentos_path %>

app/views/lancamentos/filtro.html.erb
<%= form_tag('/lancamentos', :method => 'get') do %>
	<div>
		Data Inicial </br>
		<%= text_field_tag "dataInicial" %>
	</div>
	<div>
		Data Final </br>
		<%= text_field_tag "dataFinal" %>
	</div>
	<div>
		Conta </br>
		<%= select "contaId", "", Conta.all.collect {|c| [c.descricao, c.id]} %>
	</div>
	<%= submit_tag "Enviar" %>
<% end %>

<script>
	$(function() {
		$( "#dataInicial, #dataFinal" ).datepicker({
			dateFormat: "dd/mm/yy"
		});
	});
</script>

app/views/lancamentos/index.html.erb
<h1>Lançamentos</h1>
<%= link_to 'Novo Lancamento', new_lancamento_path %>

<table id="tabela">
    <thead>
      <tr>
        <th>OK</th>
        <th>Data</th>
        <th>Referencia</th>
        <th>Evento</th>
        <th>Credito</th>
        <th>Debito</th>
        <th>Saldo</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td>Saldo anterior</td>
            <td></td>
            <td></td>
            <td></td>
            <td><%= @saldo_inicial.round(2) %></td>
            <td></td>
        </tr>
        <% @lancamentos.each do |lancamento| %>
          <tr id="linha_<%= lancamento.id %>">
            <td><%= check_box_tag "confirmado_#{lancamento.id}", lancamento.id, lancamento.confirmado ? true : false, {:onchange => "alterarCheck(this);"} %></td>
            <td><%= lancamento.data.strftime("%d/%m/%Y") %></td>
            <td><%= lancamento.referencia %></td>
            <td><%= lancamento.evento.descricao %></td>
            <td><%=  !lancamento.evento.debito ? lancamento.valor.round(2) : "" %></td>
            <td><%=  lancamento.evento.debito ? lancamento.valor.round(2) : "" %></td>
            <td><%= lancamento.saldo.round(2)  %></td>
            <td>
                <%= link_to 'Alterar', edit_lancamento_path(lancamento) %>
                <%= link_to 'Excluir', "#", :onclick => "apagarRegistro(#{lancamento.id})" %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

<br />


<script type="text/javascript">
    $(document).ready(function(){
        oTable = $("#tabela").dataTable({});

        oTable.fnSort( [ [1,'asc'] ] );
    });

    var apagarRegistro = function(id){
        var id = id;
        $.get( '/lancamento/apagar_lancamento',
            {id : id},
            function(r){
                if( r ){
                    $('#linha_' + id).hide("slow");
                }else{
                    alert('Erro ao tentar excluir. Consulte analista!');
                }
            }
        );
    }


    var  alterarCheck = function(elemento){
        var id = elemento.value
        $.get('/lancamento/confirmado',
            {id:id},
            function(retorno){});
    }
    
</script>

app/views/lancamentos/new.html.erb
<h1>Novo Lançamento</h1>

<%= render 'form' %>

<%= link_to 'Back', lancamentos_path %>

app/views/lancamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Confirmado:</b>
  <%= @lancamento.confirmado %>
</p>

<p>
  <b>Data:</b>
  <%= @lancamento.data %>
</p>

<p>
  <b>Evento:</b>
  <%= @lancamento.evento.descricao %>
</p>

<p>
  <b>Debito:</b>
  <%= @lancamento.evento.debito %>
</p>

<p>
  <b>Valor:</b>
  <%= @lancamento.valor %>
</p>


<%= link_to 'Edit', edit_lancamento_path(@lancamento) %> |
<%= link_to 'Back', lancamentos_path %>