config/routes.rb
Movimentobancario::Application.routes.draw do

  devise_for :views

  resources :produtos

  resources :prazos

  resources :grupo_eventos

  resources :eventos

  resources :contas

  resources :lancamentos
  #alterar status de confirmação do lançamento
  match "/lancamento/confirmado" => "lancamentos#confirmado"
  #filtro para listagem de lançamentos
  match "/lancamento/filtro" => "lancamentos#filtro"
  #apagar lançamento
  match "/lancamento/apagar_lancamento" => "lancamentos#apagar_lancamento"

  get "dashboard/index"

  root :to => 'dashboard#index'

  get "pages/index"

  devise_for :user
  #espera arquivo sitef
  match "/importacao/sitef" => "importacao#sitef"
  #espera arquivo softawy
  match "/importacao/softway" => "importacao#softway"
  #exibe registro do arquivo sitef
  match "/importacao/sitefExibirRegistros" => "importacao#sitefExibirRegistros"
  #processa arquivo sitef: salva registro sitef e cria lançamentos
  match "/importacao/processaRegistrosSitef" => "importacao#processaRegistrosSitef"


  
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  attr_accessible :descricao, :inativo, :limite
  has_many :lancamentos
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :debito, :descricao, :grupo_evento_id, :prazo_id
  
  has_many :lancamentos
  belongs_to :grupo_evento
  belongs_to :prazo
end

app/models/grupo_evento.rb
class GrupoEvento < ActiveRecord::Base
  attr_accessible :descricao
  has_many :eventos
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  attr_accessible :confirmado, :data, :evento, :valor, :debito, :evento_id, :conta_id, :referencia
  validates_presence_of :data, :valor, :conta
  
  belongs_to :evento
  belongs_to :conta
end

app/models/prazo.rb
class Prazo < ActiveRecord::Base
  attr_accessible :descricao, :funcao
  has_many :produtos
  has_many :evento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :descricao, :descricao_sitef, :prazo_id, :conta_id, :evento_id, :taxa, :valor_lancamento
  validates :descricao, uniqueness: true
  validates :descricao_sitef, uniqueness: true
  
  belongs_to :prazo
  belongs_to :conta
  belongs_to :evento 

  def self.descricoesSitef
  	descricoes = Array.new
  	produtos = self.find(:all, :select => 'descricao_sitef')
  	produtos.each do |produto|
  		descricoes << produto.descricao_sitef
  	end
  	return descricoes
  end
end

app/models/registro_sitef.rb
class RegistroSitef < ActiveRecord::Base
  attr_accessible :nome_produto, :nsu_sitef, :autorizador, :codi_resp, :codigo_transacao, :data_lancamen, 
	  	:estado_trasacao, :indentifi_pdv, :lancado, :nsu_host, :num_par, :numero_cartao_banco_ag_co, :valor
  validates :nsu_sitef, uniqueness: true
end

app/models/sitef_file.rb
class SitefFile < ActiveRecord::Base
  attr_accessible :arquivo, :dia_correspondente
  has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_sitef.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_sitef.prn"

validates_attachment_presence :arquivo
validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/softway_files.rb
class SoftwayFiles < ActiveRecord::Base
  	attr_accessible :arquivo, :dia_correspondente
  	has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_softway.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_softway.prn"

	validates_attachment_presence :arquivo
	validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  # GET /contas
  # GET /contas.json
  def index
    @contas = Conta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contas }
    end
  end

  # GET /contas/1
  # GET /contas/1.json
  def show
    @conta = Conta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conta }
    end
  end

  # GET /contas/new
  # GET /contas/new.json
  def new
    @conta = Conta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conta }
    end
  end

  # GET /contas/1/edit
  def edit
    @conta = Conta.find(params[:id])
  end

  # POST /contas
  # POST /contas.json
  def create
    @conta = Conta.new(params[:conta])

    respond_to do |format|
      if @conta.save
        format.html { redirect_to @conta, notice: 'Conta was successfully created.' }
        format.json { render json: @conta, status: :created, location: @conta }
      else
        format.html { render action: "new" }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contas/1
  # PUT /contas/1.json
  def update
    @conta = Conta.find(params[:id])

    respond_to do |format|
      if @conta.update_attributes(params[:conta])
        format.html { redirect_to @conta, notice: 'Conta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.json
  def destroy
    @conta = Conta.find(params[:id])
    @conta.destroy

    respond_to do |format|
      format.html { redirect_to contas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/importacao_helper.rb
module ImportacaoHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prazos_helper.rb
module PrazosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sitef_helper.rb
module SitefHelper
end

app/views/contas/_form.html.erb
<%= form_for(@conta) do |f| %>
  <% if @conta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conta.errors.count, "error") %> prohibited this conta from being saved:</h2>

      <ul>
      <% @conta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :limite %><br />
    <%= f.text_field :limite %>
  </div>
  <div class="field">
    <%= f.label :inativo %><br />
    <%= f.check_box :inativo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contas/edit.html.erb
<h1>Editing conta</h1>

<%= render 'form' %>

<%= link_to 'Show', @conta %> |
<%= link_to 'Back', contas_path %>

app/views/contas/index.html.erb
<h1>Listing contas</h1>

<table>
  <tr>
    <th>Descricao</th>
    <th>Limite</th>
    <th>Inativo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contas.each do |conta| %>
  <tr>
    <td><%= conta.descricao %></td>
    <td><%= conta.limite %></td>
    <td><%= conta.inativo %></td>
    <td><%= link_to 'Show', conta %></td>
    <td><%= link_to 'Edit', edit_conta_path(conta) %></td>
    <td><%= link_to 'Destroy', conta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conta', new_conta_path %>

app/views/contas/new.html.erb
<h1>New conta</h1>

<%= render 'form' %>

<%= link_to 'Back', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @conta.descricao %>
</p>

<p>
  <b>Limite:</b>
  <%= @conta.limite %>
</p>

<p>
  <b>Inativo:</b>
  <%= @conta.inativo %>
</p>


<%= link_to 'Edit', edit_conta_path(@conta) %> |
<%= link_to 'Back', contas_path %>