config/routes.rb
Movimentobancario::Application.routes.draw do

  devise_for :views

  resources :produtos

  resources :prazos

  resources :grupo_eventos

  resources :eventos

  resources :contas

  resources :lancamentos
  #alterar status de confirmação do lançamento
  match "/lancamento/confirmado" => "lancamentos#confirmado"
  #filtro para listagem de lançamentos
  match "/lancamento/filtro" => "lancamentos#filtro"
  #apagar lançamento
  match "/lancamento/apagar_lancamento" => "lancamentos#apagar_lancamento"

  get "dashboard/index"

  root :to => 'dashboard#index'

  get "pages/index"

  devise_for :user
  #espera arquivo sitef
  match "/importacao/sitef" => "importacao#sitef"
  #espera arquivo softawy
  match "/importacao/softway" => "importacao#softway"
  #exibe registro do arquivo sitef
  match "/importacao/sitefExibirRegistros" => "importacao#sitefExibirRegistros"
  #processa arquivo sitef: salva registro sitef e cria lançamentos
  match "/importacao/processaRegistrosSitef" => "importacao#processaRegistrosSitef"


  
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  attr_accessible :descricao, :inativo, :limite
  has_many :lancamentos
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :debito, :descricao, :grupo_evento_id, :prazo_id
  
  has_many :lancamentos
  belongs_to :grupo_evento
  belongs_to :prazo
end

app/models/grupo_evento.rb
class GrupoEvento < ActiveRecord::Base
  attr_accessible :descricao
  has_many :eventos
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  attr_accessible :confirmado, :data, :evento, :valor, :debito, :evento_id, :conta_id, :referencia
  validates_presence_of :data, :valor, :conta
  
  belongs_to :evento
  belongs_to :conta
end

app/models/prazo.rb
class Prazo < ActiveRecord::Base
  attr_accessible :descricao, :funcao
  has_many :produtos
  has_many :evento
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :descricao, :descricao_sitef, :prazo_id, :conta_id, :evento_id, :taxa, :valor_lancamento
  validates :descricao, uniqueness: true
  validates :descricao_sitef, uniqueness: true
  
  belongs_to :prazo
  belongs_to :conta
  belongs_to :evento 

  def self.descricoesSitef
  	descricoes = Array.new
  	produtos = self.find(:all, :select => 'descricao_sitef')
  	produtos.each do |produto|
  		descricoes << produto.descricao_sitef
  	end
  	return descricoes
  end
end

app/models/registro_sitef.rb
class RegistroSitef < ActiveRecord::Base
  attr_accessible :nome_produto, :nsu_sitef, :autorizador, :codi_resp, :codigo_transacao, :data_lancamen, 
	  	:estado_trasacao, :indentifi_pdv, :lancado, :nsu_host, :num_par, :numero_cartao_banco_ag_co, :valor
  validates :nsu_sitef, uniqueness: true
end

app/models/sitef_file.rb
class SitefFile < ActiveRecord::Base
  attr_accessible :arquivo, :dia_correspondente
  has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_sitef.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_sitef.prn"

validates_attachment_presence :arquivo
validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/softway_files.rb
class SoftwayFiles < ActiveRecord::Base
  	attr_accessible :arquivo, :dia_correspondente
  	has_attached_file :arquivo,
                  :url  => "/public/arquivos_sitef/arquivo_softway.prn",
                  :path => ":rails_root/public/arquivos_sitef/arquivo_softway.prn"

	validates_attachment_presence :arquivo
	validates_attachment_size :arquivo, :less_than => 5.megabytes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/importacao_helper.rb
module ImportacaoHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prazos_helper.rb
module PrazosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sitef_helper.rb
module SitefHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :debido %><br />
    <%= f.check_box :debito %>
  </div>
  
  <div class="field">
    <%= f.label "Grupo Evento" %><br />
    <%= f.collection_select :grupo_evento_id, GrupoEvento.all, :id, :descricao %>
  </div>
</br>
  <div class="actions">
    <%= f.submit 'Criar evento'%>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h3>Eventos</h3>

<table>
  <tr>
    <th>Descricao</th>
    <th>Debito</th>
    <th>Grupo evento</th>
    <th>Ações</th>
  </tr>

<% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.descricao %></td>
    <td><%= evento.debito %></td>
    <td><%= evento.grupo_evento.descricao %></td>
    <td>
      <%= link_to 'Show', evento %>
      <%= link_to 'Edit', edit_evento_path(evento) %>
      <%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>Novo evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @evento.descricao %>
</p>

<p>
  <b>Debido:</b>
  <%= @evento.debito %>
</p>

<p>
  <b>Grupo evento:</b>
  <%= @evento.grupo_evento_id %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>